/* 
 * Merchant API
 *
 * ZipMoney Merchant API Initial build
 *
 * OpenAPI spec version: 2017-03-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MerchantApi.Api;
using MerchantApi.Model;
using MerchantApi.Client;
using System.Reflection;

namespace MerchantApi.Test
{
    /// <summary>
    ///  Class for testing ChargeCollection
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ChargeCollectionTests
    {
        // TODO uncomment below to declare an instance variable for ChargeCollection
        //private ChargeCollection instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ChargeCollection
            //instance = new ChargeCollection();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ChargeCollection
        /// </summary>
        [Test]
        public void ChargeCollectionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ChargeCollection
            //Assert.IsInstanceOfType<ChargeCollection> (instance, "variable 'instance' is a ChargeCollection");
        }

        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Test]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }

    }

}
