/* 
 * Merchant API
 *
 * ZipMoney Merchant API Initial build
 *
 * OpenAPI spec version: 2017-03-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MerchantApi.Api;
using MerchantApi.Model;
using MerchantApi.Client;
using System.Reflection;

namespace MerchantApi.Test
{
    /// <summary>
    ///  Class for testing CheckoutFeaturesTokenisation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CheckoutFeaturesTokenisationTests
    {
        // TODO uncomment below to declare an instance variable for CheckoutFeaturesTokenisation
        //private CheckoutFeaturesTokenisation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CheckoutFeaturesTokenisation
            //instance = new CheckoutFeaturesTokenisation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CheckoutFeaturesTokenisation
        /// </summary>
        [Test]
        public void CheckoutFeaturesTokenisationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CheckoutFeaturesTokenisation
            //Assert.IsInstanceOfType<CheckoutFeaturesTokenisation> (instance, "variable 'instance' is a CheckoutFeaturesTokenisation");
        }

        /// <summary>
        /// Test the property 'Required'
        /// </summary>
        [Test]
        public void RequiredTest()
        {
            // TODO unit test for the property 'Required'
        }

    }

}
