/* 
 * Merchant API
 *
 * ZipMoney Merchant API Initial build
 *
 * OpenAPI spec version: 2017-03-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MerchantApi.Api;
using MerchantApi.Model;
using MerchantApi.Client;
using System.Reflection;

namespace MerchantApi.Test
{
    /// <summary>
    ///  Class for testing CreateCheckoutRequestFeatures
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CreateCheckoutRequestFeaturesTests
    {
        // TODO uncomment below to declare an instance variable for CreateCheckoutRequestFeatures
        //private CreateCheckoutRequestFeatures instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CreateCheckoutRequestFeatures
            //instance = new CreateCheckoutRequestFeatures();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreateCheckoutRequestFeatures
        /// </summary>
        [Test]
        public void CreateCheckoutRequestFeaturesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CreateCheckoutRequestFeatures
            //Assert.IsInstanceOfType<CreateCheckoutRequestFeatures> (instance, "variable 'instance' is a CreateCheckoutRequestFeatures");
        }

        /// <summary>
        /// Test the property 'Tokenisation'
        /// </summary>
        [Test]
        public void TokenisationTest()
        {
            // TODO unit test for the property 'Tokenisation'
        }

    }

}
