/* 
 * Merchant API
 *
 * ZipMoney Merchant API Initial build
 *
 * OpenAPI spec version: 2017-03-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MerchantApi.Api;
using MerchantApi.Model;
using MerchantApi.Client;
using System.Reflection;

namespace MerchantApi.Test
{
    /// <summary>
    ///  Class for testing CreateCheckoutRequestFeaturesTokenisation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CreateCheckoutRequestFeaturesTokenisationTests
    {
        // TODO uncomment below to declare an instance variable for CreateCheckoutRequestFeaturesTokenisation
        //private CreateCheckoutRequestFeaturesTokenisation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CreateCheckoutRequestFeaturesTokenisation
            //instance = new CreateCheckoutRequestFeaturesTokenisation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreateCheckoutRequestFeaturesTokenisation
        /// </summary>
        [Test]
        public void CreateCheckoutRequestFeaturesTokenisationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CreateCheckoutRequestFeaturesTokenisation
            //Assert.IsInstanceOfType<CreateCheckoutRequestFeaturesTokenisation> (instance, "variable 'instance' is a CreateCheckoutRequestFeaturesTokenisation");
        }

        /// <summary>
        /// Test the property 'Required'
        /// </summary>
        [Test]
        public void RequiredTest()
        {
            // TODO unit test for the property 'Required'
        }

    }

}
