/* 
 * Merchant API
 *
 * ZipMoney Merchant API Initial build
 *
 * OpenAPI spec version: 2017-03-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MerchantApi.Api;
using MerchantApi.Model;
using MerchantApi.Client;
using System.Reflection;

namespace MerchantApi.Test
{
    /// <summary>
    ///  Class for testing Flightadditionaldetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FlightadditionaldetailsTests
    {
        // TODO uncomment below to declare an instance variable for Flightadditionaldetails
        //private Flightadditionaldetails instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Flightadditionaldetails
            //instance = new Flightadditionaldetails();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Flightadditionaldetails
        /// </summary>
        [Test]
        public void FlightadditionaldetailsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Flightadditionaldetails
            //Assert.IsInstanceOfType<Flightadditionaldetails> (instance, "variable 'instance' is a Flightadditionaldetails");
        }

        /// <summary>
        /// Test the property 'DepartureDate'
        /// </summary>
        [Test]
        public void DepartureDateTest()
        {
            // TODO unit test for the property 'DepartureDate'
        }
        /// <summary>
        /// Test the property 'FlightNumber'
        /// </summary>
        [Test]
        public void FlightNumberTest()
        {
            // TODO unit test for the property 'FlightNumber'
        }
        /// <summary>
        /// Test the property 'AircraftType'
        /// </summary>
        [Test]
        public void AircraftTypeTest()
        {
            // TODO unit test for the property 'AircraftType'
        }
        /// <summary>
        /// Test the property '_Class'
        /// </summary>
        [Test]
        public void _ClassTest()
        {
            // TODO unit test for the property '_Class'
        }
        /// <summary>
        /// Test the property 'Origin'
        /// </summary>
        [Test]
        public void OriginTest()
        {
            // TODO unit test for the property 'Origin'
        }
        /// <summary>
        /// Test the property 'Destination'
        /// </summary>
        [Test]
        public void DestinationTest()
        {
            // TODO unit test for the property 'Destination'
        }
        /// <summary>
        /// Test the property 'Duration'
        /// </summary>
        [Test]
        public void DurationTest()
        {
            // TODO unit test for the property 'Duration'
        }
        /// <summary>
        /// Test the property 'Passengers'
        /// </summary>
        [Test]
        public void PassengersTest()
        {
            // TODO unit test for the property 'Passengers'
        }
        /// <summary>
        /// Test the property 'Stopovers'
        /// </summary>
        [Test]
        public void StopoversTest()
        {
            // TODO unit test for the property 'Stopovers'
        }

    }

}
