/* 
 * Merchant API
 *
 * ZipMoney Merchant API Initial build
 *
 * OpenAPI spec version: 2017-03-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MerchantApi.Api;
using MerchantApi.Model;
using MerchantApi.Client;
using System.Reflection;

namespace MerchantApi.Test
{
    /// <summary>
    ///  Class for testing OrderShippingTracking
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OrderShippingTrackingTests
    {
        // TODO uncomment below to declare an instance variable for OrderShippingTracking
        //private OrderShippingTracking instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OrderShippingTracking
            //instance = new OrderShippingTracking();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OrderShippingTracking
        /// </summary>
        [Test]
        public void OrderShippingTrackingInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OrderShippingTracking
            //Assert.IsInstanceOfType<OrderShippingTracking> (instance, "variable 'instance' is a OrderShippingTracking");
        }

        /// <summary>
        /// Test the property 'Uri'
        /// </summary>
        [Test]
        public void UriTest()
        {
            // TODO unit test for the property 'Uri'
        }
        /// <summary>
        /// Test the property 'Number'
        /// </summary>
        [Test]
        public void NumberTest()
        {
            // TODO unit test for the property 'Number'
        }
        /// <summary>
        /// Test the property 'Carrier'
        /// </summary>
        [Test]
        public void CarrierTest()
        {
            // TODO unit test for the property 'Carrier'
        }

    }

}
