/* 
 * Merchant API
 *
 * ZipMoney Merchant API Initial build
 *
 * OpenAPI spec version: 2017-03-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MerchantApi.Api;
using MerchantApi.Model;
using MerchantApi.Client;
using System.Reflection;

namespace MerchantApi.Test
{
    /// <summary>
    ///  Class for testing OrderShipping
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OrderShippingTests
    {
        // TODO uncomment below to declare an instance variable for OrderShipping
        //private OrderShipping instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OrderShipping
            //instance = new OrderShipping();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OrderShipping
        /// </summary>
        [Test]
        public void OrderShippingInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OrderShipping
            //Assert.IsInstanceOfType<OrderShipping> (instance, "variable 'instance' is a OrderShipping");
        }

        /// <summary>
        /// Test the property 'Pickup'
        /// </summary>
        [Test]
        public void PickupTest()
        {
            // TODO unit test for the property 'Pickup'
        }
        /// <summary>
        /// Test the property 'Tracking'
        /// </summary>
        [Test]
        public void TrackingTest()
        {
            // TODO unit test for the property 'Tracking'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Test]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }

    }

}
