/* 
 * Merchant API
 *
 * ZipMoney Merchant API Initial build
 *
 * OpenAPI spec version: 2017-03-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MerchantApi.Api;
using MerchantApi.Model;
using MerchantApi.Client;
using System.Reflection;

namespace MerchantApi.Test
{
    /// <summary>
    ///  Class for testing OrderItemAdditionalDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OrderItemAdditionalDetailsTests
    {
        // TODO uncomment below to declare an instance variable for OrderItemAdditionalDetails
        //private OrderItemAdditionalDetails instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OrderItemAdditionalDetails
            //instance = new OrderItemAdditionalDetails();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OrderItemAdditionalDetails
        /// </summary>
        [Test]
        public void OrderItemAdditionalDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OrderItemAdditionalDetails
            //Assert.IsInstanceOfType<OrderItemAdditionalDetails> (instance, "variable 'instance' is a OrderItemAdditionalDetails");
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
