/* 
 * Merchant API
 *
 * ZipMoney Merchant API Initial build
 *
 * OpenAPI spec version: 2017-03-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MerchantApi.Api;
using MerchantApi.Model;
using MerchantApi.Client;
using System.Reflection;

namespace MerchantApi.Test
{
    /// <summary>
    ///  Class for testing ShopperStatistics
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ShopperStatisticsTests
    {
        // TODO uncomment below to declare an instance variable for ShopperStatistics
        //private ShopperStatistics instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ShopperStatistics
            //instance = new ShopperStatistics();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ShopperStatistics
        /// </summary>
        [Test]
        public void ShopperStatisticsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ShopperStatistics
            //Assert.IsInstanceOfType<ShopperStatistics> (instance, "variable 'instance' is a ShopperStatistics");
        }

        /// <summary>
        /// Test the property 'AccountCreated'
        /// </summary>
        [Test]
        public void AccountCreatedTest()
        {
            // TODO unit test for the property 'AccountCreated'
        }
        /// <summary>
        /// Test the property 'SalesTotalCount'
        /// </summary>
        [Test]
        public void SalesTotalCountTest()
        {
            // TODO unit test for the property 'SalesTotalCount'
        }
        /// <summary>
        /// Test the property 'SalesTotalAmount'
        /// </summary>
        [Test]
        public void SalesTotalAmountTest()
        {
            // TODO unit test for the property 'SalesTotalAmount'
        }
        /// <summary>
        /// Test the property 'SalesAvgAmount'
        /// </summary>
        [Test]
        public void SalesAvgAmountTest()
        {
            // TODO unit test for the property 'SalesAvgAmount'
        }
        /// <summary>
        /// Test the property 'SalesMaxAmount'
        /// </summary>
        [Test]
        public void SalesMaxAmountTest()
        {
            // TODO unit test for the property 'SalesMaxAmount'
        }
        /// <summary>
        /// Test the property 'RefundsTotalAmount'
        /// </summary>
        [Test]
        public void RefundsTotalAmountTest()
        {
            // TODO unit test for the property 'RefundsTotalAmount'
        }
        /// <summary>
        /// Test the property 'PreviousChargeback'
        /// </summary>
        [Test]
        public void PreviousChargebackTest()
        {
            // TODO unit test for the property 'PreviousChargeback'
        }
        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Test]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }
        /// <summary>
        /// Test the property 'LastLogin'
        /// </summary>
        [Test]
        public void LastLoginTest()
        {
            // TODO unit test for the property 'LastLogin'
        }
        /// <summary>
        /// Test the property 'HasPreviousPurchases'
        /// </summary>
        [Test]
        public void HasPreviousPurchasesTest()
        {
            // TODO unit test for the property 'HasPreviousPurchases'
        }
        /// <summary>
        /// Test the property 'FraudCheckResult'
        /// </summary>
        [Test]
        public void FraudCheckResultTest()
        {
            // TODO unit test for the property 'FraudCheckResult'
        }

    }

}
