/* 
 * Merchant API
 *
 * ZipMoney Merchant API Initial build
 *
 * OpenAPI spec version: 2017-03-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using MerchantApi.Client;
using MerchantApi.Api;

namespace MerchantApi.Test
{
    /// <summary>
    ///  Class for testing CustomersApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class CustomersApiTests
    {
        private CustomersApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new CustomersApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CustomersApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' CustomersApi
            //Assert.IsInstanceOfType(typeof(CustomersApi), instance, "instance is a CustomersApi");
        }

        
        /// <summary>
        /// Test CustomersGet
        /// </summary>
        [Test]
        public void CustomersGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //instance.CustomersGet(id);
            
        }
        
        /// <summary>
        /// Test CustomersList
        /// </summary>
        [Test]
        public void CustomersListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.CustomersList();
            
        }
        
    }

}
