/* 
 * Merchant API
 *
 * ZipMoney Merchant API Initial build
 *
 * OpenAPI spec version: 2017-03-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Diagnostics;
using MerchantApi.Api;
using MerchantApi.Model;

namespace MerchantApi.Example
{
    /// <summary>
    ///  Class for testing OrdersApi

    public class ApiExample
    {
        AuthorizationApi authorizationApi;
        OrdersApi ordersApi;

        public void main()
        { 
            // Configure API key authorization, get an Access Token, Create an Order, Get an Order

            try
            {
                // Setup Authorization
                authorizationApi = new AuthorizationApi("https://merchant-auth-nz.sandbox.zip.co");
                authorizationApi.Configuration.ClientId = "Your Client Id";
                authorizationApi.Configuration.ClientSecret = "Your Client Secret";

                // Create Acces Token
                var authorization = authorizationApi.AuthorizationCreateToken();
                Debug.WriteLine(authorization);
            }
            catch (Exception e)
            {
                Debug.Print("Exception when calling AuthorizationApi: " + e.Message );
            }
	        
            try
            {
                // Create Order
		        ordersApi = new OrdersApi("https://sandbox.zip.co/nz/api");
                var createOrderRequest = CreateRequest(CreateOrderRequest.PaymentFlowEnum.Payment);
                var authorization = authorizationApi.AuthorizationCreateToken();

                // Create Order
                var createOrderResponse = ordersApi.OrderCreate(authorization, "Idempotency-Key", createOrderRequest);
                Debug.WriteLine(createOrderResponse);
		
		        // Get Order
		        var id = createOrderResponse.OrderId;
                var order = ordersApi.OrderGet(id);
                Debug.WriteLine(order);
            }
            catch (Exception e)
            {
                Debug.Print("Exception when calling OrdersApi: " + e.Message);
            }
        }
    }
}
