/* 
 * Merchant API
 *
 * ZipMoney Merchant API Initial build
 *
 * OpenAPI spec version: 2017-03-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using MerchantApi.Client;
using MerchantApi.Api;
using MerchantApi.Model;

namespace MerchantApi.Test
{
    /// <summary>
    ///  Class for testing SettlementsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class SettlementsApiTests
    {
        private SettlementsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new SettlementsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SettlementsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' SettlementsApi
            //Assert.IsInstanceOfType(typeof(SettlementsApi), instance, "instance is a SettlementsApi");
        }

        
        /// <summary>
        /// Test SettlementsGet
        /// </summary>
        [Test]
        public void SettlementsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.SettlementsGet(id);
            //Assert.IsInstanceOf<Settlement> (response, "response is Settlement");
        }
        
        /// <summary>
        /// Test SettlementsList
        /// </summary>
        [Test]
        public void SettlementsListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.SettlementsList();
            
        }
        
    }

}
