/* 
 * Merchant API
 *
 * ZipMoney Merchant API Initial build
 *
 * OpenAPI spec version: 2017-03-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace MerchantApi.Model
{
    /// <summary>
    /// CheckoutFeaturesTokenisation
    /// </summary>
    [DataContract]
    public partial class CheckoutFeaturesTokenisation :  IEquatable<CheckoutFeaturesTokenisation>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CheckoutFeaturesTokenisation" /> class.
        /// </summary>
        /// <param name="Required">States if the tokenisation is required to proceed with the checkout. (default to true).</param>
        public CheckoutFeaturesTokenisation(bool? Required = true)
        {
            // use default value if no "Required" provided
            if (Required == null)
            {
                this.Required = true;
            }
            else
            {
                this.Required = Required;
            }
        }
        
        /// <summary>
        /// States if the tokenisation is required to proceed with the checkout.
        /// </summary>
        /// <value>States if the tokenisation is required to proceed with the checkout.</value>
        [DataMember(Name="required", EmitDefaultValue=false)]
        public bool? Required { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CheckoutFeaturesTokenisation {\n");
            sb.Append("  Required: ").Append(Required).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as CheckoutFeaturesTokenisation);
        }

        /// <summary>
        /// Returns true if CheckoutFeaturesTokenisation instances are equal
        /// </summary>
        /// <param name="other">Instance of CheckoutFeaturesTokenisation to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CheckoutFeaturesTokenisation other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Required == other.Required ||
                    this.Required != null &&
                    this.Required.Equals(other.Required)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Required != null)
                    hash = hash * 59 + this.Required.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
