/* 
 * Merchant API
 *
 * ZipMoney Merchant API Initial build
 *
 * OpenAPI spec version: 2017-03-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace MerchantApi.Model
{
    /// <summary>
    /// Additional features for this request
    /// </summary>
    [DataContract]
    public partial class CreateCheckoutRequestFeatures :  IEquatable<CreateCheckoutRequestFeatures>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateCheckoutRequestFeatures" /> class.
        /// </summary>
        /// <param name="Tokenisation">Tokenisation.</param>
        public CreateCheckoutRequestFeatures(CreateCheckoutRequestFeaturesTokenisation Tokenisation = default(CreateCheckoutRequestFeaturesTokenisation))
        {
            this.Tokenisation = Tokenisation;
        }
        
        /// <summary>
        /// Gets or Sets Tokenisation
        /// </summary>
        [DataMember(Name="tokenisation", EmitDefaultValue=false)]
        public CreateCheckoutRequestFeaturesTokenisation Tokenisation { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreateCheckoutRequestFeatures {\n");
            sb.Append("  Tokenisation: ").Append(Tokenisation).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as CreateCheckoutRequestFeatures);
        }

        /// <summary>
        /// Returns true if CreateCheckoutRequestFeatures instances are equal
        /// </summary>
        /// <param name="other">Instance of CreateCheckoutRequestFeatures to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateCheckoutRequestFeatures other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Tokenisation == other.Tokenisation ||
                    this.Tokenisation != null &&
                    this.Tokenisation.Equals(other.Tokenisation)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Tokenisation != null)
                    hash = hash * 59 + this.Tokenisation.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
